hflip_p: 0.5
vflip_p: 0.5
rotate90_p: 0.5
color_jitter:
  brightness: 0.2
  contrast: 0.15
  saturation: 0.1
  hue: 0.02
sharpness:
  factor: 1.3
  p: 0.25
gaussian_blur:
  kernel_size: 3
  sigma_min: 0.1
  sigma_max: 1.0
  p: 0.2
gauss_noise_p: 0.15