# Configuration file for training a Faster R-CNN model on the BCCD dataset
experiment_name: bccd_faster_rcnn

dataset:
  root: "../BCCD_Dataset"
  train_subdir: "train"
  test_subdir: "test"
  image_size: 480
  labels:
    WBC: 1
    RBC: 2
    Platelets: 3

training:
  epochs: 10
  batch_size: 4
  learning_rate: 0.001
  optimizer: "SGD"
  weight_decay: 0.0005
  momentum: 0.9

model:
  type: "faster_rcnn"
  num_classes: 3

augmentation:
  hflip_p: 0.5
  vflip_p: 0.5
  rotate90_p: 0.5
  color_jitter:
    brightness: 0.2
    contrast: 0.15
    saturation: 0.1
    hue: 0.02
  sharpness:
    factor: 1.3
    p: 0.25
  gaussian_blur:
    kernel_size: 3
    sigma_min: 0.1
    sigma_max: 1.0
    p: 0.2
  gauss_noise_p: 0.15

logging:
  use_mlflow: true
  tracking_uri: http://127.0.0.1:5000