FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

LABEL maintainer="hieplt"
LABEL organization="mlops"

RUN apt-get update && apt-get install -y --no-install-recommends \
    git libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN pip install --upgrade pip
RUN pip install torchinfo==1.8.0 opencv-python==4.12.0.88 albumentations==2.0.8 mlflow==3.3.1

COPY ./utils ./utils
COPY ./train.py ./train.py
COPY ./bccd_dataset.py ./bccd_dataset.py
COPY ./model.py ./model.py
COPY ./config.yaml ./config.yaml

WORKDIR /workspace

# CMD ["python", "training.py"]